### ISSUE TITLE
Fix frontend deployment

### ISSUE THREAD

**Issue by AkseliManninen** [AkseliManninen/lunssi#48]
Backend deployment was successful but frontend failed. This might be @yannjor related to the latest frontend PR?

<img width="1271" alt="image" src="https://github.com/user-attachments/assets/5cf98e3c-5394-45de-9ec5-f195ea8cf6fa">

**Comment by yannjor** [comment]
Builds locally on my machine. I think the reason may be that it's missing the `BACKEND_API_URL` env variable in the CI job

**Comment by AkseliManninen** [comment]
I'll try to solve by adding it to repository variables.

**Comment by yannjor** [comment]
Might need to add here too: https://github.com/AkseliManninen/lunssi/blob/ed7c00f49596e314f96190ae9c8ad56183360473/.github/workflows/deploy.yml#L43

**Comment by AkseliManninen** [comment]
Frontend job still fails for some reason. I tried even to hardcode the URL to see if that is the reason. Any ideas?

I deployed from my computer the lates frontend.

<img width="1271" alt="image" src="https://github.com/user-attachments/assets/be173084-2117-4177-bcbe-ee1b703d55b9">

<img width="1271" alt="image" src="https://github.com/user-attachments/assets/6be54f56-f5c8-4e3a-b89c-ef2e43a6435d">

**Comment by yannjor** [comment]
Hmm, I can try to invesigate this a bit later tonight. However looks like the backend is currently deployed to the frontend url atm: https://lunssi.fly.dev/
